      - name: Debug (list files + tool versions)
        run: |
          set -eux
          pwd
          ls -la
          ls -la postman || true
          node -v
          npm -v
          newman -v || true

      - name: Run Newman
        run: |
          set -eux
          mkdir -p reports
          newman run "postman/API Testing Demo - JSONPlaceholder.postman_collection.json" \
            -e "postman/Local - JSONPlaceholder.postman_environment.json" \
            -r htmlextra --reporter-htmlextra-export reports/report.html
